---
- hosts: all
  user: orenault
  sudo: yes
  roles:
    - krb-client

- hosts: kdc_server
  user: orenault
  sudo: yes
  roles:
    - kdc

- hosts: ambari_server
  user: orenault
  sudo: yes
  roles:
    - ambari-kerberos-setup
